[build]
rustflags = ["-g", "-C", "target-cpu=native"]
rustdocflags = ["-C", "target-cpu=native"]

# ^ https://github.com/rui314/mold#mold-a-modern-linker
#   Desired, also in rustflags: "-Zshare-generics=y"

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-fuse-ld=zld",
    "-C", "link-arg=-L/usr/local/lib"
]
