repos:
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    hooks:
      - id: alejandra-system

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy

  - repo: local
    hooks:
    - id: nextest
      name: nextest
      description: Run test suite with cargo-nextest
      entry: cargo nextest
      language: system
      types: [rust]
      args: ["run"]