ledger: ~/.mina-indexer/mainnet.json
non_genesis_ledger: false
root_hash: 3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ
startup_dir: ~/.mina-indexer/startup-blocks
watch_dir: ~/.mina-indexer/watch-blocks
database_dir: ~/.mina-indexer/database
log_dir: ~/.mina-indexer/logs
keep_non_canonical_blocks: true
log_level: info
log_level_stdout: trace
prune_interval: 10
canonical_update_threshold: 2
snapshot_path: None