#! /bin/sh
#
# Populates the "$4" directory with precomputed block records from the Mina
# "$3" network, beginning with blocks of height "$1" and ending with blocks of
# height "$2" (less than 1000).

set -eu

MY_DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"

MIN_LENGTH=$1
MAX_LENGTH=$2
NETWORK=$3
OUT_DIR=$4

for LENGTH in `seq $MIN_LENGTH $MAX_LENGTH`
do
  cp "${MY_DIR}"/data/initial-blocks/"${NETWORK}"-"${LENGTH}"-*.json "${OUT_DIR}"/
done
