#!/usr/bin/env bash
# shellcheck disable=SC2046,SC2086,SC2002

set -x
set -eu
set -o pipefail

# Collect the binaries under test and the test ledgers.
SRC="$(CDPATH='' cd "$(dirname "$0")" && pwd)"/..
IDXR="$SRC"/rust/target/release/mina-indexer
LEDGER="$SRC"/data/genesis_ledgers/mainnet.json
STAKING_LEDGERS="$SRC"/tests/data/staking_ledgers
LOCKED_CSV="$SRC"/data/locked.csv
SUMMARY_SCHEMA="$SRC"/tests/data/json-schemas/summary.json

# The rest of this script's logic assumes that the testing is done from within
# this temporary directory.
TEST_DIR="$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')"
DOMAIN_SOCKET_PATH="$TEST_DIR"/mina-indexer.sock
cd "$TEST_DIR"

# Invoke this function when exiting this script for any reason.
test_cleanup() {
    err=$?
    if [ $err != 0 ]; then
        echo "Test failed ($test): $err"
        teardown
        exit 1
    fi
    rm -rf "${TEST_DIR}"
}

trap test_cleanup EXIT

ephemeral_port() {
    set +e
    LOW_BOUND=49152
    RANGE=16384
    while true; do
        CANDIDATE=$(( LOW_BOUND + (RANDOM % RANGE) ))
        if ! (echo "" >/dev/tcp/127.0.0.1/${CANDIDATE}) >/dev/null 2>&1; then
            echo $CANDIDATE
            break
        fi
    done
    set -e
}

wait_for_socket() {
    num_retries=0
    # We retry 100 times before giving up because there is a good chance that
    # the machine is heavily loaded.
    while [ $num_retries -lt 100 ]; do
        if [ -S "$DOMAIN_SOCKET_PATH" ]; then
            return
        fi
        (( num_retries+=1 ))
        sleep 0.5
    done
}

wait_forever_for_socket() {
    while true; do
        if [ -S "$DOMAIN_SOCKET_PATH" ]; then
            return
        fi
        sleep 10
    done
}

idxr() {
    RUST_BACKTRACE=full "$IDXR" --domain-socket-path "$DOMAIN_SOCKET_PATH" "$@"
}

idxr_server() {
    RUST_BACKTRACE=full "$IDXR" --domain-socket-path "$DOMAIN_SOCKET_PATH" server "$@" &
    echo $! > idxr_pid
}

kill_idxr() {
    echo "Shutting down Mina Indexer."
    idxr server shutdown ||
        true  # Because the mina-indexer may already be shut down.

    # Wait no more than 10 seconds for the process.
    timeout 10s pwait -F ./idxr_pid ||
        true  # Because the process may already be gone, yielding an error.

    echo "Deleting PID file."
    rm -f ./idxr_pid
}

idxr_server_start() {
    port=$(ephemeral_port)
    idxr_server start --web-port "$port" "$@"
}

idxr_server_sync() {
    port=$(ephemeral_port)
    idxr_server sync --web-port "$port" \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        "$@"
}
idxr_server_replay() {
    port=$(ephemeral_port)
    idxr_server replay --web-port "$port" \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
}

stage_mainnet_blocks() {
    local BLOCKS_FETCHER="$SRC"/tests/stage-blocks
    "$BLOCKS_FETCHER" 2 "$1" mainnet "$2"
}

dl_mainnet() {
    local BLOCKS_FETCHER="$SRC"/tests/stage-initial-blocks
    "$BLOCKS_FETCHER" 2 "$1" mainnet "$2"
}

dl_mainnet_single() {
    local BLOCKS_FETCHER="$SRC"/tests/stage-initial-blocks
    "$BLOCKS_FETCHER" "$1" "$1" mainnet "$2"
}

dl_mainnet_range() {
    local BLOCKS_FETCHER="$SRC"/tests/stage-initial-blocks
    "$BLOCKS_FETCHER" "$1" "$2" mainnet "$3"
}

assert() {
    expected="$1"
    actual="$2"

    if [ "$expected" != "$actual" ]; then
        echo "Test Failed: Expected $expected, but got $actual"
        exit 1
    else
        echo "Test Passed!"
    fi
}

assert_directory_exists() {
    directory="$1"

    if [ ! -d "$directory" ]; then
        echo "Test Failed: Expected directory $directory to exist, but it does not."
        exit 1
    else
        echo "Test Passed: Directory $directory exists."
    fi
}

setup() {
    echo "setup"
    mkdir blocks
    mkdir staking-ledgers
    mkdir database
}

teardown() {
    kill_idxr
    rm -rf ./blocks
    rm -rf ./staking-ledgers
    rm -rf ./database
    rm -f "$DOMAIN_SOCKET_PATH"
}

test_indexer_cli_reports() {
    test=test_indexer_cli_reports

    # Indexer reports usage with no arguments
    ( "$IDXR" 2>&1 || true ) | grep -iq "Usage:"

    # Indexer reports usage for server subcommand
    idxr_server 2>&1 |
        grep -iq "Usage: mina-indexer server"

    # Indexer server cli subcommand works with default args
    idxr_server --help 2>/dev/null

    idxr_server start --help 2>&1 |
        grep -iq "Usage: mina-indexer server start"

    idxr_server start-via-config --help 2>&1 |
        grep -iq "Usage: mina-indexer server start-via-config"

    idxr_server sync --help 2>&1 |
        grep -iq "Usage: mina-indexer server sync"

    idxr_server replay --help 2>&1 |
        grep -iq "Usage: mina-indexer server replay"

    # Indexer reports usage for client subcommands
    idxr accounts --help 2>&1 |
        grep -iq "Usage: mina-indexer accounts"

    idxr accounts public-key --help 2>&1 |
        grep -iq "Usage: mina-indexer accounts public-key"

    idxr blocks --help 2>&1 |
        grep -iq "Usage: mina-indexer blocks"

    idxr blocks best-tip --help 2>&1 |
        grep -iq "Usage: mina-indexer blocks best-tip"

    idxr blocks height --help 2>&1 |
        grep -iq "Usage: mina-indexer blocks height"

    idxr blocks slot --help 2>&1 |
        grep -iq "Usage: mina-indexer blocks slot"

    idxr blocks public-key --help 2>&1 |
        grep -iq "Usage: mina-indexer blocks public-key"

    idxr checkpoints --help 2>&1 |
        grep -iq "Usage: mina-indexer checkpoints"

    idxr checkpoints create --help 2>&1 |
        grep -iq "Usage: mina-indexer checkpoints create"

    idxr ledgers best --help 2>&1 |
        grep -iq "Usage: mina-indexer ledgers best"

    idxr ledgers --help 2>&1 |
        grep -iq "Usage: mina-indexer ledgers"

    idxr ledgers height --help 2>&1 |
        grep -iq "Usage: mina-indexer ledgers height"

    idxr staking-ledgers delegations --help 2>&1 |
        grep -iq "Usage: mina-indexer staking-ledgers delegations"

    idxr staking-ledgers public-key --help 2>&1 |
        grep -iq "Usage: mina-indexer staking-ledgers public-key"

    idxr staking-ledgers epoch --help 2>&1 |
        grep -iq "Usage: mina-indexer staking-ledgers epoch"

    idxr staking-ledgers hash --help 2>&1 |
        grep -iq "Usage: mina-indexer staking-ledgers hash"

    idxr server shutdown --help 2>&1 |
        grep -iq "Usage: mina-indexer server shutdown"

    idxr summary --help 2>&1 |
        grep -iq "Usage: mina-indexer summary"

    idxr transactions hash --help 2>&1 |
        grep -iq "Usage: mina-indexer transactions hash"

    idxr transactions public-key --help 2>&1 |
        grep -iq "Usage: mina-indexer transactions public-key"

    idxr transactions state-hash --help 2>&1 |
        grep -iq "Usage: mina-indexer transactions state-hash"

    idxr transactions state-hash --help 2>&1 |
        grep -iq "Usage: mina-indexer transactions state-hash"

    idxr internal-commands public-key --help 2>&1 |
        grep -iq "Usage: mina-indexer internal-commands public-key"

    idxr internal-commands state-hash --help 2>&1 |
        grep -iq "Usage: mina-indexer internal-commands state-hash"

    idxr snarks public-key --help 2>&1 |
        grep -iq "Usage: mina-indexer snarks public-key"

    idxr snarks state-hash --help 2>&1 |
        grep -iq "Usage: mina-indexer snarks state-hash"
}

# Indexer server starts up without any precomputed blocks
test_server_startup() {
    test=test_server_startup

    setup
    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    result=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    assert '3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ' $result

    teardown
}

# Indexer server ipc is available during initialization
test_ipc_is_available_immediately() {
    test=test_ipc_is_available_immediately

    setup
    dl_mainnet 100 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database \
        --genesis-ledger "$LEDGER" \
        --genesis-hash 3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ
    wait_for_socket

    idxr summary
    teardown
}

# Indexer server starts and creates directories with minimal args
test_startup_dirs_get_created() {
    test=test_startup_dirs_get_created

    setup
    idxr_server_start \
        --blocks-dir ./startup-blocks \
        --block-watch-dir ./watch-blocks \
        --staking-ledgers-dir ./startup-ledgers \
        --staking-ledger-watch-dir ./watch-ledgers \
        --database-dir ./database
    wait_for_socket

    assert_directory_exists "./startup-blocks"
    assert_directory_exists "./watch-blocks"
    assert_directory_exists "./startup-ledgers"
    assert_directory_exists "./watch-ledgers"
    assert_directory_exists "./database"

    teardown
}

# Indexer server reports correct balance for Genesis Ledger Account
test_account_balance_cli() {
    test=test_account_balance_cli

    setup
    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    result=$(idxr accounts public-key --public-key B62qqDJCQsfDoHJvJCh1hgTpiVbmgBg8SbNKLMXsjuVsX5pxCELDyFk | jq -r .balance)
    assert '148837200000000' $result

    teardown
}

# Indexer server returns the correct account
test_account_public_key_json() {
    test=test_account_public_key_json

    setup
    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    result=$(idxr accounts public-key --public-key B62qqDJCQsfDoHJvJCh1hgTpiVbmgBg8SbNKLMXsjuVsX5pxCELDyFk | jq -r .public_key)
    assert 'B62qqDJCQsfDoHJvJCh1hgTpiVbmgBg8SbNKLMXsjuVsX5pxCELDyFk' $result

    teardown
}

# Indexer summary returns the correct canonical root
test_canonical_root() {
    test=test_canonical_root

    setup
    dl_mainnet 15 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    length=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)

    assert 5 $length
    assert '3NKQUoBfi9vkbuqtDJmSEYBQrcSo4GjwG8bPCiii4yqM8AxEQvtY' $hash

    teardown
}

# Indexer server handles canonical threshold correctly
test_canonical_threshold() {
    test=test_canonical_threshold

    num_seq_blocks=15
    canonical_threshold=2

    setup
    dl_mainnet $num_seq_blocks ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database \
        --canonical-threshold $canonical_threshold
    wait_for_socket

    hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    length=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)

    assert $(( num_seq_blocks - canonical_threshold )) $length
    assert '3NKHEHXsScTUd6kMDtoB4tf45MavdXv91qo3HZkLKrkc8XpX5CDv' $hash

    teardown
}

# Indexer server returns the correct best tip
test_best_tip() {
    test=test_best_tip

    setup
    dl_mainnet 15 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    # best tip query
    hash=$(idxr blocks best-tip | jq -r .state_hash)
    canonicity=$(idxr blocks best-tip | jq -r .canonicity)
    length=$(idxr blocks best-tip | jq -r .blockchain_length)
    canonicity_v=$(idxr blocks best-tip --verbose | jq -r .canonicity)

    # witness tree summary
    wt_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    wt_length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)

    assert $wt_hash $hash
    assert $wt_length $length
    assert 'Canonical' $canonicity
    assert 'Canonical' $canonicity_v

    teardown
}

# Indexer server returns the correct blocks for height and slot queries
test_blocks() {
    test=test_blocks

    setup
    dl_mainnet 10 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    # basic height query
    hash=$(idxr blocks height --height 10 | jq -r .[0].state_hash)
    slot=$(idxr blocks height --height 10 | jq -r .[0].global_slot_since_genesis)
    length=$(idxr blocks height --height 10 | jq -r .[0].blockchain_length)
    canonicity=$(idxr blocks height --height 10 | jq -r .[0].canonicity)

    # verbose height query
    hash_v=$(idxr blocks height --height 10 --verbose | jq -r .[0].state_hash)
    length_v=$(idxr blocks height --height 10 --verbose | jq -r .[0].blockchain_length)
    canonicity_v=$(idxr blocks height --height 10 --verbose | jq -r .[0].canonicity)

    # witness tree summary
    wt_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    wt_length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)

    assert 9 $slot
    assert $wt_hash $hash
    assert $wt_hash $hash_v
    assert $wt_length $length
    assert $wt_length $length_v
    assert 'Canonical' $canonicity
    assert 'Canonical' $canonicity_v

    # basic slot query
    hash=$(idxr blocks slot --slot 9 | jq -r .[0].state_hash)
    slot=$(idxr blocks slot --slot 9 | jq -r .[0].global_slot_since_genesis)
    length=$(idxr blocks slot --slot 9 | jq -r .[0].blockchain_length)
    canonicity=$(idxr blocks slot --slot 9 | jq -r .[0].canonicity)

    # verbose slot query
    hash_v=$(idxr blocks slot --slot 9 --verbose | jq -r .[0].state_hash)
    length_v=$(idxr blocks slot --slot 9 --verbose | jq -r .[0].blockchain_length)
    canonicity_v=$(idxr blocks slot --slot 9 --verbose | jq -r .[0].canonicity)

    assert 9 $slot
    assert $wt_hash $hash
    assert $wt_hash $hash_v
    assert $wt_length $length
    assert $wt_length $length_v
    assert 'Canonical' $canonicity
    assert 'Canonical' $canonicity_v

    # basic public key query
    hash=$(idxr blocks public-key --public-key B62qpbZkvpHZ1a5nsTbANuRtrdw4YraTyA4nvJDm6HpP1YMC9QStxX3 | jq -r .[0].state_hash)
    slot=$(idxr blocks public-key --public-key B62qpbZkvpHZ1a5nsTbANuRtrdw4YraTyA4nvJDm6HpP1YMC9QStxX3 | jq -r .[0].global_slot_since_genesis)
    length=$(idxr blocks public-key --public-key B62qpbZkvpHZ1a5nsTbANuRtrdw4YraTyA4nvJDm6HpP1YMC9QStxX3 | jq -r .[0].blockchain_length)
    canonicity=$(idxr blocks public-key --public-key B62qpbZkvpHZ1a5nsTbANuRtrdw4YraTyA4nvJDm6HpP1YMC9QStxX3 | jq -r .[0].canonicity)

    # verbose public key query
    hash_v=$(idxr blocks public-key --public-key B62qpbZkvpHZ1a5nsTbANuRtrdw4YraTyA4nvJDm6HpP1YMC9QStxX3 --verbose | jq -r .[0].state_hash)
    length_v=$(idxr blocks public-key --public-key B62qpbZkvpHZ1a5nsTbANuRtrdw4YraTyA4nvJDm6HpP1YMC9QStxX3 --verbose | jq -r .[0].blockchain_length)
    canonicity_v=$(idxr blocks public-key --public-key B62qpbZkvpHZ1a5nsTbANuRtrdw4YraTyA4nvJDm6HpP1YMC9QStxX3 --verbose | jq -r .[0].canonicity)

    assert 9 $slot
    assert $wt_hash $hash
    assert $wt_hash $hash_v
    assert $wt_length $length
    assert $wt_length $length_v
    assert 'Canonical' $canonicity
    assert 'Canonical' $canonicity_v

    # height 10 = slot 9
    slot=$(idxr blocks slot --slot 9 | jq -r .)
    height=$(idxr blocks height --height 10 | jq -r .)
    assert "$slot" "$height"

    # write at height to file
    file=./blocks_at_height.json
    idxr blocks height --height 10 --path $file

    height=$(cat $file | jq -r .[0].blockchain_length)
    slot=$(cat $file | jq -r .[0].global_slot_since_genesis)

    assert 9 $slot
    assert 10 $height

    # write at slot to file
    file=./blocks_at_slot.json
    idxr blocks slot --slot 9 --path $file

    height=$(cat $file | jq -r .[0].blockchain_length)
    slot=$(cat $file | jq -r .[0].global_slot_since_genesis)

    assert 9 $slot
    assert 10 $height

    # write at public key to file
    file=./blocks_at_pk.json
    idxr blocks public-key --public-key B62qpbZkvpHZ1a5nsTbANuRtrdw4YraTyA4nvJDm6HpP1YMC9QStxX3 --path $file

    height=$(cat $file | jq -r .[0].blockchain_length)
    slot=$(cat $file | jq -r .[0].global_slot_since_genesis)

    assert 9 $slot
    assert 10 $height

    teardown
}

# Indexer handles copied blocks correctly
test_block_copy() {
    test=test_block_copy

    setup
    dl_mainnet 10 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database \
        --log-level debug
    wait_for_socket

    # start without block 11
    best_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    best_length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)
    canonical_hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    canonical_length=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)

    assert 10 $best_length
    assert 1 $canonical_length
    assert '3NKGgTk7en3347KH81yDra876GPAUSoSePrfVKPmwR1KHfMpvJC5' $best_hash
    assert '3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ' $canonical_hash

    # add block 11
    dl_mainnet_single 11 ./blocks
    sleep 1
    ls -l ./blocks

    # check
    best_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    best_length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)
    canonical_hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    canonical_length=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)

    assert 11 $best_length
    assert 1 $canonical_length
    assert '3NLMeYAFXxsmhSFtLHFxdtjGcfHTVFmBmBF8uTJvP4Ve5yEmxYeA' $best_hash
    assert '3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ' $canonical_hash

    teardown
}

# Indexer handles missing blocks correctly
test_missing_blocks() {
    test=test_missing_blocks

    setup
    dl_mainnet 10 ./blocks
    dl_mainnet_range 12 20 ./blocks # missing 11
    dl_mainnet_range 22 30 ./blocks # missing 21

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database \
        --log-level debug
    wait_for_socket

    # start out missing block 11 & 21
    num_dangling=$(idxr summary --json | jq -r .witness_tree.num_dangling)
    best_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    best_length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)
    canonical_hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    canonical_length=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)

    assert 4 $num_dangling
    assert 10 $best_length
    assert 1 $canonical_length
    assert '3NKGgTk7en3347KH81yDra876GPAUSoSePrfVKPmwR1KHfMpvJC5' $best_hash
    assert '3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ' $canonical_hash

    # add missing block which connects the dangling branches
    dl_mainnet_single 21 ./blocks
    sleep 1

    # dangling branches combine
    # no new canonical blocks
    num_dangling=$(idxr summary --json | jq -r .witness_tree.num_dangling)
    best_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    best_length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)
    canonical_hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    canonical_length=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)

    assert 3 $num_dangling
    assert 10 $best_length
    assert 1 $canonical_length
    assert '3NKGgTk7en3347KH81yDra876GPAUSoSePrfVKPmwR1KHfMpvJC5' $best_hash
    assert '3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ' $canonical_hash

    # add remaining missing block
    dl_mainnet_single 11 ./blocks
    sleep 1

    # dangling branches move into the root branch
    num_dangling=$(idxr summary --json | jq -r .witness_tree.num_dangling)
    best_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    best_length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)
    canonical_hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    canonical_length=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)

    assert 0 $num_dangling
    assert 30 $best_length
    assert 20 $canonical_length
    assert '3NLpGhdRifLr31DGc61jUhsAdZiTy7EUw8cap41jrmzbTem5hc3V' $best_hash
    assert '3NLPpt5SyVnD1U5uJAqR3DL1Cqj5dG26SuWutRQ6AQpbQtQUWSYA' $canonical_hash

    teardown
}

# Indexer server returns the correct best chain
test_best_chain() {
    test=test_best_chain

    setup
    mkdir best_chain
    dl_mainnet 12 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    result=$(idxr chain best --num 1 | jq -r .[0].state_hash)
    assert '3NKkJDmNZGYdKVDDJkkamGdvNzASia2SXxKpu18imps7KqbNXENY' $result

    result=$(idxr chain best --verbose | jq -r .[0].state_hash)
    assert '3NKkJDmNZGYdKVDDJkkamGdvNzASia2SXxKpu18imps7KqbNXENY' $result

    # best chain with bounds
    bounds=$(idxr chain best \
        --start-state-hash 3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R \
        --end-state-hash 3NKQUoBfi9vkbuqtDJmSEYBQrcSo4GjwG8bPCiii4yqM8AxEQvtY \
        | jq -r .[0].state_hash)
    assert '3NKQUoBfi9vkbuqtDJmSEYBQrcSo4GjwG8bPCiii4yqM8AxEQvtY' $bounds

    bounds=$(idxr chain best \
        --start-state-hash '3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R' \
        --end-state-hash '3NKQUoBfi9vkbuqtDJmSEYBQrcSo4GjwG8bPCiii4yqM8AxEQvtY' \
        | jq -r .[1].state_hash)
    assert '3NL9qBsNibXPm5Nh8cSg5CCqrbzX5VUVY9gJzAbg7EVCF3hfhazG' $bounds

    bounds=$(idxr chain best --start-state-hash '3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R' \
        --end-state-hash '3NKQUoBfi9vkbuqtDJmSEYBQrcSo4GjwG8bPCiii4yqM8AxEQvtY' \
        | jq -r .[2].state_hash)
    assert '3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R' $bounds

    # write best chain to file
    file=./best_chain/best_chain.json
    idxr chain best --path $file
    file_result=$(cat $file | jq -r .[0].state_hash)
    assert '3NKkJDmNZGYdKVDDJkkamGdvNzASia2SXxKpu18imps7KqbNXENY' $file_result

    idxr chain best --verbose --path $file
    file_result=$(cat $file | jq -r .[0].state_hash)
    assert '3NKkJDmNZGYdKVDDJkkamGdvNzASia2SXxKpu18imps7KqbNXENY' $file_result

    rm -rf best_chain
    teardown
}

# Indexer server returns correct ledgers
test_ledgers() {
    test=test_ledgers

    setup
    mkdir ledgers
    dl_mainnet 15 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    pk='B62qp1RJRL7x249Z6sHCjKm1dbkpUWHRdiQbcDaz1nWUGa9rx48tYkR'

    # canonical ledgers match
    canonical_hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    canonical_height=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)

    hash_balance=$(idxr ledgers hash --hash $canonical_hash | jq -r .${pk}.balance)
    height_balance=$(idxr ledgers height --height $canonical_height | jq -r .${pk}.balance)
    assert '607904750000000' $hash_balance
    assert '607904750000000' $height_balance

    # best ledgers match
    best_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    best_height=$(idxr summary --json | jq -r .witness_tree.best_tip_length)

    best_result=$(idxr ledgers best | jq -r .${pk}.balance)
    hash_result=$(idxr ledgers hash --hash $best_hash | jq -r .${pk}.balance)
    height_balance=$(idxr ledgers height --height $best_height | jq -r .${pk}.balance)

    assert '607904750000000' $best_result
    assert '607904750000000' $hash_result
    assert '607904750000000' $height_balance

    # write ledgers to file
    file=./ledgers/best-block-$best_height-$best_hash.json
    idxr ledgers best --path $file

    file_result=$(cat $file | jq -r .${pk}.balance)
    assert '607904750000000' $file_result
    rm -f $file

    file=./ledgers/best-ledger-$best_height-$best_hash.json
    idxr ledgers hash --hash $best_hash --path $file

    file_result=$(cat $file | jq -r .${pk}.balance)
    assert '607904750000000' $file_result
    rm -f $file

    file=./ledgers/ledger-height-$best_height-$best_hash.json
    idxr ledgers height --height $best_height --path $file

    file_result=$(cat $file | jq -r .${pk}.balance)
    assert '607904750000000' $file_result
    rm -f $file

    rm -rf ledgers
    teardown
}

# Indexer server syncs with existing Speedb
test_sync() {
    test=test_sync

    setup
    dl_mainnet 15 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    kill_idxr

    # add more blocks to the watch dir while not indexing
    dl_mainnet_range 16 20 ./blocks

    # sync from previous indexer db
    idxr_server_sync --database-dir ./database
    sleep 1

    # post-sync results
    post_best_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    post_best_length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)
    post_canonical_hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    post_canonical_length=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)

    # includes blocks added to watch dir while down
    assert 20 $post_best_length
    assert 10 $post_canonical_length
    assert '3NLPpt5SyVnD1U5uJAqR3DL1Cqj5dG26SuWutRQ6AQpbQtQUWSYA' $post_best_hash
    assert '3NKGgTk7en3347KH81yDra876GPAUSoSePrfVKPmwR1KHfMpvJC5' $post_canonical_hash

    teardown
}

# Indexer server replays events
test_replay() {
    test=test_replay

    setup
    dl_mainnet 15 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    kill_idxr

    # add more blocks to the watch dir while not indexing
    dl_mainnet_range 16 20 ./blocks

    # replay events from previous indexer instance
    idxr_server_replay
    sleep 1

    # post-replay results
    root_hash_replay=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    root_length_replay=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)
    best_hash_replay=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    best_length_replay=$(idxr summary --json | jq -r .witness_tree.best_tip_length)
    num_blocks_replay=$(idxr summary --json | jq -r .blocks_processed)

    assert 29 $num_blocks_replay
    assert 20 $best_length_replay
    assert 10 $root_length_replay
    assert '3NLPpt5SyVnD1U5uJAqR3DL1Cqj5dG26SuWutRQ6AQpbQtQUWSYA' $best_hash_replay
    assert '3NKGgTk7en3347KH81yDra876GPAUSoSePrfVKPmwR1KHfMpvJC5' $root_hash_replay

    teardown
}

# Indexer server returns correct transactions
test_transactions() {
    test=test_transactions

    setup
    mkdir transactions
    dl_mainnet 13 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    # basic pk transaction queries
    transactions=$(idxr transactions public-key --public-key B62qp1RJRL7x249Z6sHCjKm1dbkpUWHRdiQbcDaz1nWUGa9rx48tYkR | jq -r .)
    amount=$(idxr transactions public-key --public-key B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy | jq -r .[0].Payment.amount)

    assert '1000' $amount
    assert '[]' $transactions

    # basic pk transaction queries - verbose
    kind=$(idxr transactions public-key --public-key B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy --verbose | jq -r .[0].command.payload.body.kind)
    amount=$(idxr transactions public-key --public-key B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy --verbose | jq -r .[0].command.payload.body.amount)
    state_hash=$(idxr transactions public-key --public-key B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy --verbose | jq -r .[0].state_hash)
    tx_hash=$(idxr transactions public-key --public-key B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy --verbose | jq -r .[0].tx_hash)
    length=$(idxr transactions public-key --public-key B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy --verbose | jq -r .[0].blockchain_length)

    assert 3 $length
    assert '1000' $amount
    assert 'Payment' $kind
    assert '3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R' $state_hash
    assert 'CkpZirFuoLVVab6x2ry4j8Ld5gMmQdak7VHW6f5C7VJYE34WAEWqa' $tx_hash

    # bounded pk transaction queries
    amount=$(idxr transactions public-key --public-key B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy \
        --start-state-hash 3NL9qBsNibXPm5Nh8cSg5CCqrbzX5VUVY9gJzAbg7EVCF3hfhazG \
        --end-state-hash 3NKXzc1hAE1bK9BSkJUhBBSznMhwW3ZxUTgdoLoqzW6SvqVFcAw5 \
        | jq -r .[0].Payment.amount)
    assert '1000' $amount

    amount=$(idxr transactions public-key --public-key B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy \
        --start-state-hash 3NLyWnjZqUECniE1q719CoLmes6WDQAod4vrTeLfN7XXJbHv6EHH \
        --end-state-hash 3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R \
        | jq -r .[0].Payment.amount)
    assert '1000' $amount

    # tx hash query
    amount=$(idxr transactions hash --hash CkpZirFuoLVVab6x2ry4j8Ld5gMmQdak7VHW6f5C7VJYE34WAEWqa | jq -r .Payment.amount)
    assert '1000' $amount

    # tx hash query - verbose
    kind=$(idxr transactions hash --hash CkpZirFuoLVVab6x2ry4j8Ld5gMmQdak7VHW6f5C7VJYE34WAEWqa --verbose | jq -r .command.payload.body.kind)
    amount=$(idxr transactions hash --hash CkpZirFuoLVVab6x2ry4j8Ld5gMmQdak7VHW6f5C7VJYE34WAEWqa --verbose | jq -r .command.payload.body.amount)
    status=$(idxr transactions hash --hash CkpZirFuoLVVab6x2ry4j8Ld5gMmQdak7VHW6f5C7VJYE34WAEWqa --verbose | jq -r .status.kind)
    tx_hash=$(idxr transactions hash --hash CkpZirFuoLVVab6x2ry4j8Ld5gMmQdak7VHW6f5C7VJYE34WAEWqa --verbose | jq -r .tx_hash)
    state_hash=$(idxr transactions hash --hash CkpZirFuoLVVab6x2ry4j8Ld5gMmQdak7VHW6f5C7VJYE34WAEWqa --verbose | jq -r .state_hash)
    length=$(idxr transactions hash --hash CkpZirFuoLVVab6x2ry4j8Ld5gMmQdak7VHW6f5C7VJYE34WAEWqa --verbose | jq -r .blockchain_length)

    assert 3 $length
    assert 'Payment' $kind
    assert '1000' $amount
    assert 'Failed' $status
    assert 'CkpZirFuoLVVab6x2ry4j8Ld5gMmQdak7VHW6f5C7VJYE34WAEWqa' $tx_hash
    assert '3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R' $state_hash

    # state hash query
    amount=$(idxr transactions state-hash --state-hash 3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R | jq -r .[0].Payment.amount)
    source=$(idxr transactions state-hash --state-hash 3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R | jq -r .[0].Payment.source)
    receiver=$(idxr transactions state-hash --state-hash 3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R | jq -r .[0].Payment.receiver)

    assert '1000' $amount
    assert 'B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy' $source
    assert 'B62qjYanmV7y9njVeH5UHkz3GYBm7xKir1rAnoY4KsEYUGLMiU45FSM' $receiver

    # state hash query - verbose
    kind=$(idxr transactions state-hash --state-hash 3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R --verbose | jq -r .[0].data.kind)
    assert 'Signed_command' $kind

    amount=$(idxr transactions state-hash --state-hash 3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R --verbose | jq -r .[0].data.payload.body.amount)
    source=$(idxr transactions state-hash --state-hash 3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R --verbose | jq -r .[0].data.payload.body.source_pk)
    receiver=$(idxr transactions state-hash --state-hash 3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R --verbose | jq -r .[0].data.payload.body.receiver_pk)
    token=$(idxr transactions state-hash --state-hash 3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R --verbose | jq -r .[0].data.payload.body.token_id)

    assert '1' $token
    assert '1000' $amount
    assert 'B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy' $source
    assert 'B62qjYanmV7y9njVeH5UHkz3GYBm7xKir1rAnoY4KsEYUGLMiU45FSM' $receiver

    # write transactions to file
    file=./transactions/transactions.json
    idxr transactions public-key --public-key B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy --path $file

    file_result=$(cat $file | jq -r .[0].Payment.amount)
    assert '1000' $file_result

    rm -rf ./transactions
    teardown
}
# Indexer server returns correct SNARK work
test_snark_work() {
    test=test_snark_work

    setup
    mkdir snark_work
    dl_mainnet 120 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database \
        --log-level debug
    wait_for_socket

    # pk SNARK work queries
    # prover has SNARK work in block 111
    fee=$(idxr snarks public-key --public-key B62qrCz3ehCqi8Pn8y3vWC9zYEB9RKsidauv15DeZxhzkxL3bKeba5h | jq -r .[0].fee)
    prover=$(idxr snarks public-key --public-key B62qrCz3ehCqi8Pn8y3vWC9zYEB9RKsidauv15DeZxhzkxL3bKeba5h | jq -r .[0].prover)
    state_hash=$(idxr snarks public-key --public-key B62qrCz3ehCqi8Pn8y3vWC9zYEB9RKsidauv15DeZxhzkxL3bKeba5h | jq -r .[0].state_hash)

    assert '0' $fee
    assert 'B62qrCz3ehCqi8Pn8y3vWC9zYEB9RKsidauv15DeZxhzkxL3bKeba5h' $prover
    assert '3NL33j16AWm3Jhjj1Ud25E54hu7HpUq4WBQcAiijEKMfXqwFJwzK' $state_hash

    # state hash SNARK work queries
    fee=$(idxr snarks state-hash --state-hash 3NL33j16AWm3Jhjj1Ud25E54hu7HpUq4WBQcAiijEKMfXqwFJwzK | jq -r .[0].fee)
    prover=$(idxr snarks state-hash --state-hash 3NL33j16AWm3Jhjj1Ud25E54hu7HpUq4WBQcAiijEKMfXqwFJwzK | jq -r .[0].prover)

    assert '0' $fee
    assert 'B62qrCz3ehCqi8Pn8y3vWC9zYEB9RKsidauv15DeZxhzkxL3bKeba5h' $prover

    # write SNARK work from public key to file
    file=./snark_work/snark_work.json
    idxr snarks public-key --public-key B62qrCz3ehCqi8Pn8y3vWC9zYEB9RKsidauv15DeZxhzkxL3bKeba5h --path $file

    fee=$(cat $file | jq -r .[0].fee)
    prover=$(cat $file | jq -r .[0].prover)
    state_hash=$(cat $file | jq -r .[0].state_hash)

    assert '0' $fee
    assert 'B62qrCz3ehCqi8Pn8y3vWC9zYEB9RKsidauv15DeZxhzkxL3bKeba5h' $prover
    assert '3NL33j16AWm3Jhjj1Ud25E54hu7HpUq4WBQcAiijEKMfXqwFJwzK' $state_hash

    # write SNARK work from block to file
    file=./snark_work/snark_work.json
    idxr snarks state-hash --state-hash 3NL33j16AWm3Jhjj1Ud25E54hu7HpUq4WBQcAiijEKMfXqwFJwzK --path $file

    fee=$(cat $file | jq -r .[0].fee)
    prover=$(cat $file | jq -r .[0].prover)

    assert '0' $fee
    assert 'B62qrCz3ehCqi8Pn8y3vWC9zYEB9RKsidauv15DeZxhzkxL3bKeba5h' $prover

    rm -rf ./snark_work
    teardown
}

# Indexer server correctly creates a db checkpoint
test_checkpoint() {
    test=test_checkpoint

    setup
    dl_mainnet 13 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    # pre-checkpoint results
    canonical_hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    canonical_length=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)
    best_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    best_length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)
    amount=$(idxr transactions public-key --public-key B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy --verbose | jq -r .[0].command.payload.body.amount)

    # create checkpoint in ./checkpoint
    idxr checkpoints create --path ./checkpoint

    # kill running indexer and remove directories
    teardown

    # sync a new indexer from checkpointed db
    setup
    idxr_server_sync --database-dir ./checkpoint
    wait_for_socket

    # post-checkpoint reults
    canonical_hash_checkpoint=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    canonical_length_checkpoint=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)
    best_hash_checkpoint=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    best_length_checkpoint=$(idxr summary --json | jq -r .witness_tree.best_tip_length)
    amount_checkpoint=$(idxr transactions public-key --public-key B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy --verbose | jq -r .[0].command.payload.body.amount)

    assert $canonical_hash $canonical_hash_checkpoint
    assert $canonical_length $canonical_length_checkpoint
    assert $best_hash $best_hash_checkpoint
    assert $best_length $best_length_checkpoint
    assert $amount $amount_checkpoint

    rm -rf ./checkpoint
    teardown
}

# Indexer server starts with many blocks
test_many_blocks() {
    test=test_many_blocks

    setup
    stage_mainnet_blocks 1000 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database \
        --ledger-cadence 100 \
        --log-level debug
    wait_forever_for_socket

    # results
    best_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    best_length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)
    canonical_hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    canonical_length=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)

    assert '1000' $best_length
    assert '990' $canonical_length
    assert '3NK9aySQJBEgAUKcWGrpbZhA4M8wL2N3cjipq3mEb4HPTuUkowEF' $canonical_hash
    assert '3NKrnCRmvomXqor8pnqrUsLv4XcofJBu8VWqAsWRirGNPszo1a66' $best_hash

    pk='B62qpJ4Q5J4LoBXgQBfq6gbXTyevFPhwMNYZEBdTSixmFq4UrdNadSN'

    # check ledgers are present
    # mainnet-100-3NKLtRnMaWAAfRvdizaeaucDPBePPKGbKw64RVcuRFtMMkE8aAD4.json
    balance=$(idxr ledgers hash --hash 3NKLtRnMaWAAfRvdizaeaucDPBePPKGbKw64RVcuRFtMMkE8aAD4 | jq -r .${pk}.balance)
    assert '502777775000000' $balance

    # mainnet-900-3NLHqp2mkmWbf4o69J4hg5cftRAAvZ5Edy7uqvJUUVvZWtD1xRrh.json
    balance=$(idxr ledgers hash --hash 3NLHqp2mkmWbf4o69J4hg5cftRAAvZ5Edy7uqvJUUVvZWtD1xRrh | jq -r .${pk}.balance)
    assert '502777775000000' $balance

    teardown
}

test_rest_endpoints() {
    test=test_rest_endpoints

    setup
    dl_mainnet 100 ./blocks
    port=$(ephemeral_port)

    idxr_server start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database \
        --log-level debug \
        --web-port "$port" \
        --web-hostname "0.0.0.0"
    wait_for_socket

    # results
    balance=$(curl --silent http://localhost:${port}/accounts/B62qrQBarKiVK11xP943pMQxnmNrfYpT7hskHLWdFXbx2K1E9wR1Vdy | jq -r .balance)
    assert '1439050000000' $balance

    # Testing blockchain summary endpoint
    curl --silent http://localhost:${port}/summary > output.json

    blockchain_length=$(cat output.json | jq -r .blockchainLength)
    assert '100' $blockchain_length

    chain_id=$(cat output.json | jq -r .chainId)
    assert '5f704cc0c82e0ed70e873f0893d7e06f148524e3f0bdae2afb02e7819a0c24d1' $chain_id

    circulating_supply=$(cat output.json | jq -r .circulatingSupply)
    assert '89031537.840039233' $circulating_supply

    # date_time=$(cat output.json | jq -r .dateTime)
    # assert 'Wed, 17 Mar 2021 07:15:00 GMT' $date_time

    epoch=$(cat output.json | jq -r .epoch)
    assert '0' $epoch

    global_slot=$(cat output.json | jq -r .globalSlot)
    assert '145' $global_slot

    locked_supply=$(cat output.json | jq -r .lockedSupply)
    assert '716354155' $locked_supply

    min_window_density=$(cat output.json | jq -r .minWindowDensity)
    assert '77' $min_window_density

    next_epoch_ledger_hash=$(cat output.json | jq -r .nextEpochLedgerHash)
    assert 'jx7buQVWFLsXTtzRgSxbYcT8EYLS8KCZbLrfDcJxMtyy4thw2Ee' $next_epoch_ledger_hash

    previous_state_hash=$(cat output.json | jq -r .previousStateHash)
    assert '3NLdywCHZmuqxS4hUnW7Uuu6sr97iifh5Ldc6m9EbzVZyLqbxqCh' $previous_state_hash

    slot=$(cat output.json | jq -r .slot)
    assert '145' $slot

    snarked_ledger_hash=$(cat output.json | jq -r .snarkedLedgerHash)
    assert 'jx7buQVWFLsXTtzRgSxbYcT8EYLS8KCZbLrfDcJxMtyy4thw2Ee' $snarked_ledger_hash

    staged_ledger_hash=$(cat output.json | jq -r .stagedLedgerHash)
    assert 'jwWHNKQPdgLxHCsBki57a6zBfNPUFkAQmsrCNq3E7Q8oiNCNdkm' $staged_ledger_hash

    staking_epoch_ledger_hash=$(cat output.json | jq -r .stakingEpochLedgerHash)
    assert 'jx7buQVWFLsXTtzRgSxbYcT8EYLS8KCZbLrfDcJxMtyy4thw2Ee' $staking_epoch_ledger_hash

    state_hash=$(cat output.json | jq -r .stateHash)
    assert '3NKLtRnMaWAAfRvdizaeaucDPBePPKGbKw64RVcuRFtMMkE8aAD4' $state_hash

    total_currency=$(cat output.json | jq -r .totalCurrency)
    assert '805385692.840039233' $total_currency

    check-jsonschema --schemafile "$SUMMARY_SCHEMA" output.json

    teardown
}

# Release version is fast
test_release() {
    test=test_release

    setup
    stage_mainnet_blocks 5000 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database \
        --log-level debug
    wait_forever_for_socket

    # results
    best_hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    best_length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)
    canonical_hash=$(idxr summary --json | jq -r .witness_tree.canonical_root_hash)
    canonical_length=$(idxr summary --json | jq -r .witness_tree.canonical_root_length)

    assert '5000' $best_length
    assert '4990' $canonical_length
    assert '3NKiyxhxfohCGpHkQg7TC1cNxHzAHbcHCUAdSM1aNt2u6dGtVrvC' $canonical_hash
    assert '3NLn1bsWFjycHNJGGLy3KSxXSW6ixmFrunn1iym5GWjTXxkt6oFi' $best_hash

    pk='B62qpJ4Q5J4LoBXgQBfq6gbXTyevFPhwMNYZEBdTSixmFq4UrdNadSN'

    # check ledgers are present
    # mainnet-100-3NKLtRnMaWAAfRvdizaeaucDPBePPKGbKw64RVcuRFtMMkE8aAD4.json
    balance=$(idxr ledgers hash --hash 3NKLtRnMaWAAfRvdizaeaucDPBePPKGbKw64RVcuRFtMMkE8aAD4 | jq -r .${pk}.balance)
    assert '502777775000000' $balance

    # mainnet-900-3NLHqp2mkmWbf4o69J4hg5cftRAAvZ5Edy7uqvJUUVvZWtD1xRrh.json
    balance=$(idxr ledgers hash --hash 3NLHqp2mkmWbf4o69J4hg5cftRAAvZ5Edy7uqvJUUVvZWtD1xRrh | jq -r .${pk}.balance)
    assert '502777775000000' $balance

    teardown
}

test_genesis_block_creator() {
    test=test_genesis_block_creator

    setup
    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database \
        --log-level debug
    wait_for_socket

    pk=B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg
    balance=$(idxr ledgers height --height 1 | jq -r .${pk}.balance)

    # verify that the genesis block winner account gets 1000 magic nanomina
    assert '1000' $balance

    teardown
}

test_txn_nonces() {
    test=test_txn_nonces

    setup
    dl_mainnet 100 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database \
        --log-level debug
    wait_for_socket

    pk=B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy

    # verify that the nonce matches what's reported from the archive node

    # after block 3
    nonce=$(idxr ledgers height --height 3 | jq -r .${pk}.nonce)
    assert '4' $nonce

    # after block 100
    nonce=$(idxr accounts public-key --public-key $pk | jq -r .nonce)
    assert '149' $nonce

    teardown
}

test_startup_staking_ledgers() {
    test=test_startup_staking_ledgers

    setup
    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir $STAKING_LEDGERS \
        --database-dir ./database
    wait_for_socket

    # epoch 0 staking ledger should be in the store, write it to a file
    idxr staking-ledgers epoch --epoch 0 --path ./epoch_0_ledger.json

    pk=B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg
    epoch0=jx7buQVWFLsXTtzRgSxbYcT8EYLS8KCZbLrfDcJxMtyy4thw2Ee

    epoch=$(cat ./epoch_0_ledger.json | jq -r .epoch)
    network=$(cat ./epoch_0_ledger.json | jq -r .network)
    ledger_hash=$(cat ./epoch_0_ledger.json | jq -r .ledger_hash)
    token=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.token)
    public_key=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.pk)
    balance=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.balance)
    delegate=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.delegate)
    voting_for=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.voting_for)
    receipt_chain_hash=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.receipt_chain_hash)

    assert '1' $token
    assert '0' $epoch
    assert $pk $delegate
    assert $pk $public_key
    assert '1000' $balance
    assert 'mainnet' $network
    assert $epoch0 $ledger_hash
    assert '3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x' $voting_for
    assert '2mzbV7WevxLuchs2dAMY4vQBS6XttnCUF8Hvks4XNBQ5qiSGGBQe' $receipt_chain_hash

    teardown
}

test_watch_staking_ledgers() {
    test=test_watch_staking_ledgers

    setup
    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --staking-ledger-watch-dir ./staking-ledgers \
        --database-dir ./database \
        --log-level debug
    wait_for_socket

    # copy epoch 0 staking ledger from data to watched directory
    cp $STAKING_LEDGERS/mainnet-0-jx7buQVWFLsXTtzRgSxbYcT8EYLS8KCZbLrfDcJxMtyy4thw2Ee.json ./staking-ledgers
    sleep 1

    # write epoch 0 ledger to file
    idxr staking-ledgers epoch --epoch 0 --path ./epoch_0_ledger.json

    # check account
    pk=B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg
    epoch0=jx7buQVWFLsXTtzRgSxbYcT8EYLS8KCZbLrfDcJxMtyy4thw2Ee

    epoch=$(cat ./epoch_0_ledger.json | jq -r .epoch)
    network=$(cat ./epoch_0_ledger.json | jq -r .network)
    ledger_hash=$(cat ./epoch_0_ledger.json | jq -r .ledger_hash)
    token=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.token)
    public_key=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.pk)
    balance=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.balance)
    delegate=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.delegate)
    voting_for=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.voting_for)
    receipt_chain_hash=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.receipt_chain_hash)

    assert '1' $token
    assert '0' $epoch
    assert $pk $delegate
    assert $pk $public_key
    assert '1000' $balance
    assert 'mainnet' $network
    assert $epoch0 $ledger_hash
    assert '3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x' $voting_for
    assert '2mzbV7WevxLuchs2dAMY4vQBS6XttnCUF8Hvks4XNBQ5qiSGGBQe' $receipt_chain_hash

    # Move epoch 42 staking ledger to watched directory
    epoch42=jxYFH645cwMMMDmDe7KnvTuKJ5Ev8zZbWtA73fDFn7Jyh8p6SwH
    cp "$STAKING_LEDGERS"/mainnet-42-"$epoch42".json ./staking-ledgers/
    sleep 1

    # write epoch 42 ledger to file
    idxr staking-ledgers epoch --epoch 42 --path ./epoch_42_ledger.json

    # check account
    pk=B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg

    epoch=$(cat ./epoch_42_ledger.json | jq -r .epoch)
    network=$(cat ./epoch_42_ledger.json | jq -r .network)
    ledger_hash=$(cat ./epoch_42_ledger.json | jq -r .ledger_hash)
    token=$(cat ./epoch_42_ledger.json | jq -r .staking_ledger.${pk}.token)
    public_key=$(cat ./epoch_42_ledger.json | jq -r .staking_ledger.${pk}.pk)
    balance=$(cat ./epoch_42_ledger.json | jq -r .staking_ledger.${pk}.balance)
    delegate=$(cat ./epoch_42_ledger.json | jq -r .staking_ledger.${pk}.delegate)
    voting_for=$(cat ./epoch_42_ledger.json | jq -r .staking_ledger.${pk}.voting_for)
    receipt_chain_hash=$(cat ./epoch_42_ledger.json | jq -r .staking_ledger.${pk}.receipt_chain_hash)

    assert '1' $token
    assert '42' $epoch
    assert $pk $delegate
    assert $pk $public_key
    assert '1000' $balance
    assert 'mainnet' $network
    assert $epoch42 $ledger_hash
    assert '3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x' $voting_for
    assert '2mzbV7WevxLuchs2dAMY4vQBS6XttnCUF8Hvks4XNBQ5qiSGGBQe' $receipt_chain_hash

    teardown
}

test_staking_delegations() {
    test=test_staking_delegations

    setup
    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir $STAKING_LEDGERS \
        --database-dir ./database \
        --log-level debug
    wait_for_socket

    # check account
    pk=B62qrxNgwAdhGYZv1BXQRt2HgopUceFyrtXZMikwsuaHu5FigRJjhwY
    epoch0=jx7buQVWFLsXTtzRgSxbYcT8EYLS8KCZbLrfDcJxMtyy4thw2Ee

    epoch=$(idxr staking-ledgers public-key --epoch 0 --public-key $pk | jq -r .epoch)
    network=$(idxr staking-ledgers public-key --epoch 0 --public-key $pk | jq -r .network)
    public_key=$(idxr staking-ledgers public-key --epoch 0 --public-key $pk | jq -r .pk)
    total_stake=$(idxr staking-ledgers public-key --epoch 0 --public-key $pk | jq -r .total_stake)
    count_delegates=$(idxr staking-ledgers public-key --epoch 0 --public-key $pk | jq -r .count_delegates)
    total_delegated=$(idxr staking-ledgers public-key --epoch 0 --public-key $pk | jq -r .total_delegated)

    assert '0' $epoch
    assert $pk $public_key
    assert 'mainnet' $network
    assert '794268782956784283' $total_stake
    assert '2' $count_delegates
    assert '57617370302858700' $total_delegated

    # write aggregated delegations to file
    file=./epoch_0_staking_delegations.json
    idxr staking-ledgers delegations --epoch 0 --path ./epoch_0_staking_delegations.json

    # check account
    file_epoch=$(cat $file | jq -r .epoch)
    file_network=$(cat $file | jq -r .network)
    file_public_key=$(cat $file | jq -r .delegations.${pk}.pk)
    file_count_delegates=$(cat $file | jq -r .delegations.${pk}.count_delegates)
    file_total_delegated=$(cat $file | jq -r .delegations.${pk}.total_delegated)

    assert $epoch $file_epoch
    assert $pk $file_public_key
    assert $network $file_network
    assert $count_delegates $file_count_delegates
    assert $total_delegated $file_total_delegated

    teardown
}

test_internal_commands() {
    test=test_internal_commands

    setup
    dl_mainnet 11 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    pk=B62qs2YyNuo1LbNo5sbhPByDDAB7NZiejFM6H1ctND5ui7wH4PWa7qm
    block=3NLMeYAFXxsmhSFtLHFxdtjGcfHTVFmBmBF8uTJvP4Ve5yEmxYeA

    kind=$(idxr internal-commands public-key --public-key $pk | jq -r .[1].kind)
    amount=$(idxr internal-commands public-key --public-key $pk | jq -r .[1].amount)
    sender=$(idxr internal-commands public-key --public-key $pk | jq -r .[1].sender)
    receiver=$(idxr internal-commands public-key --public-key $pk | jq -r .[1].receiver)
    state_hash=$(idxr internal-commands public-key --public-key $pk | jq -r .[1].state_hash)

    assert $pk $receiver
    assert $block $state_hash
    assert '20000000' $amount
    assert 'Fee_transfer' $kind
    assert 'B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy' $sender

    kind=$(idxr internal-commands public-key --public-key $pk | jq -r .[0].kind)
    amount=$(idxr internal-commands public-key --public-key $pk | jq -r .[0].amount)
    receiver=$(idxr internal-commands public-key --public-key $pk | jq -r .[0].receiver)
    state_hash=$(idxr internal-commands public-key --public-key $pk | jq -r .[0].state_hash)

    assert $pk $receiver
    assert 'Coinbase' $kind
    assert $block $state_hash
    assert '720000000000' $amount

    # write internal commands for public key to file
    file=./internal_commands.json
    idxr internal-commands public-key --public-key $pk --path $file

    pk_kind=$(cat $file | jq -r .[0].kind)
    pk_amount=$(cat $file | jq -r .[0].amount)
    pk_receiver=$(cat $file | jq -r .[0].receiver)
    pk_state_hash=$(cat $file | jq -r .[0].state_hash)

    assert $amount $pk_amount
    assert 'Coinbase'  $pk_kind
    assert $receiver $pk_receiver
    assert $state_hash $pk_state_hash

    # write internal commands for block to file
    idxr internal-commands state-hash --state-hash $block --path $file

    hash_kind=$(cat $file | jq -r .[0].kind)
    hash_amount=$(cat $file | jq -r .[0].amount)
    hash_receiver=$(cat $file | jq -r .[0].receiver)
    hash_state_hash=$(cat $file | jq -r .[0].state_hash)

    assert $pk_kind $hash_kind
    assert $pk_amount $hash_amount
    assert $pk_receiver $hash_receiver
    assert $pk_state_hash $hash_state_hash

    teardown
}

# Indexer correctly starts from config
test_start_from_config() {
    test=test_start_from_config

    setup
    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket
    teardown

    cp $LEDGER ./mainnet.json
    cp $LOCKED_CSV ./locked.csv

    setup
    dl_mainnet 15 ./blocks

    port=$(ephemeral_port)
    file=./config.json
    echo "
    { \"genesis_ledger\": \"./mainnet.json\",
      \"genesis_hash\": \"3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ\",
      \"blocks_dir\": \"./blocks\",
      \"block_watch_dir\": \"./blocks\",
      \"staking_ledgers_dir\": \"./staking-ledgers\",
      \"staking_ledger_watch_dir\": \"./staking-ledgers\",
      \"database_dir\": \"./database\",
      \"log_level\": \"info\",
      \"ledger_cadence\": 100,
      \"reporting_freq\": 1000,
      \"prune_interval\": 10,
      \"canonical_threshold\": 10,
      \"canonical_update_threshold\": 2,
      \"locked_supply_csv\": \"./locked.csv\",
      \"web_hostname\": \"localhost\",
      \"web_port\": ${port}
    }" > $file
    idxr_server start-via-config -p $file
    wait_for_socket

    hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)

    assert 15 $length
    assert '3NKkVW47d5Zxi7zvKufBrbiAvLzyKnFgsnN9vgCw65sffvHpv63M' $hash

    teardown
}

# Indexer correctly starts without blocks dir
test_start_without_blocks_dir() {
    test=test_start_without_blocks_dir

    setup
    idxr_server_start \
        --block-watch-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    dl_mainnet 15 ./blocks
    sleep 1

    hash=$(idxr summary --json | jq -r .witness_tree.best_tip_hash)
    length=$(idxr summary --json | jq -r .witness_tree.best_tip_length)

    assert 15 $length
    assert '3NKkVW47d5Zxi7zvKufBrbiAvLzyKnFgsnN9vgCw65sffvHpv63M' $hash

    teardown
}

# Indexer correctly starts without staking ledgers dir
test_start_without_ledgers_dir() {
    test=test_start_without_ledgers_dir

    setup
    idxr_server_start \
        --ledgers-watch-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    # copy epoch 0 staking ledger from data to watched directory
    cp $STAKING_LEDGERS/mainnet-0-jx7buQVWFLsXTtzRgSxbYcT8EYLS8KCZbLrfDcJxMtyy4thw2Ee.json ./staking-ledgers
    sleep 1

    # write epoch 0 ledger to file
    idxr staking-ledgers epoch --epoch 0 --path ./epoch_0_ledger.json

    # check account
    pk=B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg
    epoch0=jx7buQVWFLsXTtzRgSxbYcT8EYLS8KCZbLrfDcJxMtyy4thw2Ee

    epoch=$(cat ./epoch_0_ledger.json | jq -r .epoch)
    network=$(cat ./epoch_0_ledger.json | jq -r .network)
    ledger_hash=$(cat ./epoch_0_ledger.json | jq -r .ledger_hash)
    token=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.token)
    public_key=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.pk)
    balance=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.balance)
    delegate=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.delegate)
    voting_for=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.voting_for)
    receipt_chain_hash=$(cat ./epoch_0_ledger.json | jq -r .staking_ledger.${pk}.receipt_chain_hash)

    assert '1' $token
    assert '0' $epoch
    assert $pk $delegate
    assert $pk $public_key
    assert '1000' $balance
    assert 'mainnet' $network
    assert $epoch0 $ledger_hash
    assert '3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x' $voting_for
    assert '2mzbV7WevxLuchs2dAMY4vQBS6XttnCUF8Hvks4XNBQ5qiSGGBQe' $receipt_chain_hash

    teardown
}

test_clean_shutdown() {
    test=test_clean_shutdown

    setup
    idxr_server_start \
        --log-level TRACE \
        --block-watch-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    echo "Sending Mina Indexer a SIGTERM"
    PID="$(cat ./idxr_pid)"
    kill "$PID"

    # Debugging: see whether the process is still present. It often is.
    ps -p "$PID" || true

    # Wait for the process, but for no more than 10 seconds.
    timeout 10s pwait -F ./idxr_pid ||
        true

    # Check the success of trying to kill the process with SIGTERM.
    if ps -p "$PID"; then
        echo "PID $PID not killed."
        exit 1
    else
        echo "PID $PID no longer present."
    fi

    teardown
}

test_block_children() {
    test=test_block_children

    setup
    dl_mainnet 10 ./blocks

    idxr_server_start \
        --blocks-dir ./blocks \
        --staking-ledger-watch-dir ./staking-ledgers \
        --database-dir ./database
    wait_for_socket

    block_5_state_hash=3NKQUoBfi9vkbuqtDJmSEYBQrcSo4GjwG8bPCiii4yqM8AxEQvtY
    children=$(idxr blocks children --state-hash $block_5_state_hash)

    assert 6 $(echo "$children" | jq -r .[0].blockchain_length)
    assert 'Canonical' $(echo "$children" | jq -r .[0].canonicity)
    assert 5 $(echo "$children" | jq -r .[0].global_slot_since_genesis)
    assert $block_5_state_hash $(echo "$children" | jq -r .[0].parent_hash)
    assert '3NKqRR2BZFV7Ad5kxtGKNNL59neXohf4ZEC5EMKrrnijB1jy4R5v' $(echo "$children" | jq -r .[0].state_hash)

    assert 6 $(echo "$children" | jq -r .[1].blockchain_length)
    assert 'Orphaned' $(echo "$children" | jq -r .[1].canonicity)
    assert 5 $(echo "$children" | jq -r .[1].global_slot_since_genesis)
    assert $block_5_state_hash $(echo "$children" | jq -r .[1].parent_hash)
    assert '3NKvdydTvLVDJ9PKAXrisjsXoZQvUy1V2sbComWyB2uyhARCJZ5M' $(echo "$children" | jq -r .[1].state_hash)

    assert 6 $(echo "$children" | jq -r .[2].blockchain_length)
    assert 'Orphaned' $(echo "$children" | jq -r .[2].canonicity)
    assert 5 $(echo "$children" | jq -r .[2].global_slot_since_genesis)
    assert $block_5_state_hash $(echo "$children" | jq -r .[2].parent_hash)
    assert '3NLM3k3Vk1qs36hZWdbWvi4sqwer3skbgPyHMWrZMBoscNLyjnY2' $(echo "$children" | jq -r .[2].state_hash)

    assert 6 $(echo "$children" | jq -r .[3].blockchain_length)
    assert 'Orphaned' $(echo "$children" | jq -r .[3].canonicity)
    assert 5 $(echo "$children" | jq -r .[3].global_slot_since_genesis)
    assert $block_5_state_hash $(echo "$children" | jq -r .[3].parent_hash)
    assert '3NKqMEewA8gvEiW7So7nZ3DN6tPnmCtHpWuAzADN5ff9wiqkGf45' $(echo "$children" | jq -r .[3].state_hash)

    teardown
}

test_accounts_gql() {
    test=test_accounts_gql

    setup
    dl_mainnet 100 ./blocks
    port=$(ephemeral_port)

    idxr_server start \
        --blocks-dir ./blocks \
        --staking-ledgers-dir ./staking-ledgers \
        --database-dir ./database \
        --log-level debug \
        --web-port "$port" \
        --web-hostname "0.0.0.0"
    wait_for_socket

    resp=$(curl -X POST -H "Content-Type: application/json" -d '{"query": "{\naccounts(query:{publicKey: \"B62qj8KB2fk59NkV4VuoTkVXHjw8VJzC3ybKrWo7zuDC9xTiWXPygEe\"}) {\n  publicKey\n    balance\n    username\n    nonce\n    delegate\n    timeLocked\n}\n}\n"}' -s http://localhost:"$port"/graphql)

    public_key='B62qj8KB2fk59NkV4VuoTkVXHjw8VJzC3ybKrWo7zuDC9xTiWXPygEe'
    delegate='B62qj8KB2fk59NkV4VuoTkVXHjw8VJzC3ybKrWo7zuDC9xTiWXPygEe'
    balance='719020000000'
    nonce='1'

    assert "$public_key" $(echo "$resp" | jq -r '.data.accounts[0].publicKey')
    assert "$nonce" $(echo "$resp" | jq -r '.data.accounts[0].nonce')
    assert "$balance" $(echo "$resp" | jq -r '.data.accounts[0].balance')
    assert "$delegate" $(echo "$resp" | jq -r '.data.accounts[0].delegate')

    teardown
}

# Check command-line arguments
if [ "$#" -eq 0 ]; then
    # No arguments provided, run all tests
    test_indexer_cli_reports
    test_server_startup
    test_ipc_is_available_immediately
    test_startup_dirs_get_created
    test_start_without_blocks_dir
    test_account_balance_cli
    test_account_public_key_json
    test_canonical_root
    test_canonical_threshold
    test_best_tip
    test_blocks
    test_block_copy
    test_missing_blocks
    test_best_chain
    test_block_children
    test_ledgers
    test_sync
    test_replay
    test_transactions
    test_snark_work
    test_checkpoint
    test_rest_endpoints
    test_genesis_block_creator
    test_txn_nonces
    test_startup_staking_ledgers
    test_watch_staking_ledgers
    test_staking_delegations
    test_internal_commands
    test_start_from_config
    test_accounts_gql
    # TODO: still not working
    # test_clean_shutdown
else
    # Run only specified tests
    for test_name in "$@"; do
        case $test_name in
            "test_accounts_gql") test_accounts_gql ;;
            "test_indexer_cli_reports") test_indexer_cli_reports ;;
            "test_server_startup") test_server_startup ;;
            "test_ipc_is_available_immediately") test_ipc_is_available_immediately ;;
            "test_startup_dirs_get_created") test_startup_dirs_get_created ;;
            "test_start_without_blocks_dir") test_start_without_blocks_dir ;;
            "test_start_without_ledgers_dir") test_start_without_ledgers_dir ;;
            "test_account_balance_cli") test_account_balance_cli ;;
            "test_account_public_key_json") test_account_public_key_json ;;
            "test_canonical_root") test_canonical_root ;;
            "test_canonical_threshold") test_canonical_threshold ;;
            "test_best_tip") test_best_tip ;;
            "test_blocks") test_blocks ;;
            "test_block_copy") test_block_copy ;;
            "test_missing_blocks") test_missing_blocks ;;
            "test_best_chain") test_best_chain ;;
            "test_block_children") test_block_children ;;
            "test_ledgers") test_ledgers ;;
            "test_sync") test_sync ;;
            "test_replay") test_replay ;;
            "test_transactions") test_transactions ;;
            "test_snark_work") test_snark_work ;;
            "test_checkpoint") test_checkpoint ;;
            "test_rest_endpoints") test_rest_endpoints ;;
            "test_genesis_block_creator") test_genesis_block_creator ;;
            "test_txn_nonces") test_txn_nonces ;;
            "test_startup_staking_ledgers") test_startup_staking_ledgers ;;
            "test_watch_staking_ledgers") test_watch_staking_ledgers ;;
            "test_staking_delegations") test_staking_delegations ;;
            "test_internal_commands") test_internal_commands ;;
            "test_start_from_config") test_start_from_config ;;
            "test_many_blocks") test_many_blocks ;;
            "test_clean_shutdown") test_clean_shutdown ;;
            "test_release") test_release ;;
            *) echo "Unknown test: $test_name" ;;
        esac
    done
fi

echo "Done"
