#! /bin/sh
#
# Populates the "$4" directory with precomputed block records from the Mina
# "$3" network, beginning with blocks of height "$1" and ending with blocks of
# height "$2".

# set -x
set -eu

MY_DIR="$(CDPATH='' cd "$(dirname "$0")" && pwd)"

# Put 10K blocks in place if they're not there already.
#
: "${VOLUMES_DIR:=/mnt}"
DEV_DIR="$VOLUMES_DIR"/mina-indexer-dev
mkdir -p "$DEV_DIR"
"$MY_DIR"/../ops/download-mina-blocks 4 "$DEV_DIR"/blocks

MIN_LENGTH=$1
MAX_LENGTH=$2
NETWORK=$3
OUT_DIR=$4

for LENGTH in $(seq "$MIN_LENGTH" "$MAX_LENGTH")
do
  mkdir -p "${OUT_DIR}"
  cp "$DEV_DIR"/blocks/"${NETWORK}"-"${LENGTH}"-*.json "${OUT_DIR}"/
done
