#! /bin/sh
#
# Populates the "$4" directory with precomputed block records from the Mina
# "$3" network, beginning with blocks of height "$1" and ending with blocks of
# height "$2".

set -x
set -eu

MIN_LENGTH=$1
MAX_LENGTH=$2
NETWORK=$3
OUT_DIR=$4

for LENGTH in $(seq "$MIN_LENGTH" "$MAX_LENGTH")
do
  mkdir -p "${OUT_DIR}"
  cp /mnt/mina-logs/mina_network_block_data/"${NETWORK}"-"${LENGTH}"-*.json "${OUT_DIR}"/
done
