#! /usr/bin/env -S ruby -w

START_BLOCK = ARGV[0]
END_BLOCK = ARGV[1]
NETWORK = ARGV[2]
DEST = ARGV[3]

require 'fileutils'

SOURCE_DIR = __dir__ + '/data/initial-blocks'
PREFIX = SOURCE_DIR + '/' + NETWORK + '-'
FileUtils.mkdir_p(DEST, verbose: true)
for block in START_BLOCK..END_BLOCK
  Dir[PREFIX + block + '-*.json'].each do |src|
    target = DEST + '/' + File.basename(src)
    unless File.exist?(target)
      FileUtils.cp(src, target, verbose: true)
    end
  end
end
