version = 1

[install]
# Rust toolchain
nightly-rust.flake = "github:nix-community/fenix/monthly#default.toolchain"
rust-lib-src.pkg-path = "rustPlatform.rustLibSrc"
rust-lib-src.pkg-group = "rust-toolchain"
libiconv.pkg-path = "libiconv"
libiconv.systems = ["aarch64-darwin", "x86_64-darwin"]

# rust-analyzer goes in its own group because it's updated
# on a different cadence from the compiler and doesn't need
# to match versions
rust-analyzer.pkg-path = "rust-analyzer"
rust-analyzer.pkg-group = "rust-analyzer"
zld.pkg-path = "zld"
zld.systems = ["aarch64-darwin", "x86_64-darwin"]
glibc.pkg-path = "glibc"
glibc.systems = ["aarch64-linux", "x86_64-linux"]
gcc.pkg-path = "gcc"
gcc.systems = ["aarch64-linux", "x86_64-linux"]
openssl.pkg-path = "openssl"
openssl.systems = ["aarch64-linux", "x86_64-linux"]

# Ruby
ruby.pkg-path = "ruby"

# Database
duckdb.pkg-path = "duckdb"

# Cargo
cargo-machete.pkg-path = "cargo-machete"
cargo-edit.pkg-path = "cargo-edit"
postgresql.pkg-path = "postgresql_17"

# Misc

[vars]

[hook]
on-activate = """
    export PGPORT="${PGPORT:-9002}"

    export PGUSER=mina_indexer
    export PGPASS=mina_indexer
    export PGDATABASE=mina_indexer
    export SESSION_SECRET="$USER-session-secret"

    # Postgres environment variables
    export PGDATA=$PWD/postgres_data
    export PGHOST=$PWD/postgres
    export LOG_PATH=$PGHOST/LOG
    export DATABASE_URL="postgresql:///$PGDATABASE?host=$PGHOST&port=$PGPORT"
    mkdir -p $PGHOST
    if [ ! -d $PGDATA ]; then
      echo 'Initializing postgresql database...'
      initdb $PGDATA --username $PGUSER -A md5 --pwfile=<(echo $PGPASS) --auth=trust
      echo "listen_addresses='*'" >> $PGDATA/postgresql.conf
      echo "unix_socket_directories='$PGHOST'" >> $PGDATA/postgresql.conf
      echo "unix_socket_permissions=0700" >> $PGDATA/postgresql.conf
    fi
"""

[profile]

[options]
systems = ["aarch64-darwin", "x86_64-darwin", "aarch64-linux", "x86_64-linux"]

[services.database]
command = "postgres start"
vars.PGUSER = "mina_indexer"
vars.PGPASSWORD = "mina_indexer"
vars.PGDATABASE = "mina_indexer"
vars.PGPORT = "9002"
