version = 1

[install]
# Rust toolchain
nightly-rust.flake = "github:nix-community/fenix/monthly#default.toolchain"
rust-lib-src.pkg-path = "rustPlatform.rustLibSrc"
rust-lib-src.pkg-group = "rust-toolchain"
libiconv.pkg-path = "libiconv"
libiconv.systems = ["aarch64-darwin", "x86_64-darwin"]

# rust-analyzer goes in its own group because it's updated
# on a different cadence from the compiler and doesn't need
# to match versions
rust-analyzer.pkg-path = "rust-analyzer"
rust-analyzer.pkg-group = "rust-analyzer"

# Linker
mold.pkg-path = "mold"
mold.systems = ["aarch64-linux", "x86_64-linux"]
zld.pkg-path = "zld"
zld.systems = ["aarch64-darwin", "x86_64-darwin"]

# Ruby
ruby.pkg-path = "ruby"

[vars]

[hook]

[profile]

[options]
systems = ["aarch64-darwin", "x86_64-darwin", "aarch64-linux", "x86_64-linux"]
