#! /bin/sh

set -eux

# TODO: re-enable when Nix build works.
exit 0

#REV="$(git rev-parse --short=8 HEAD)"
#IMAGE=mina-indexer:"$REV"
#docker --version
#nix build .#dockerImage
#docker load < ./result
#docker run --rm -it "$IMAGE" \
#  mina-indexer server start --help
#docker image rm "$IMAGE"
