#! /usr/bin/env -S ruby -w
# -*- mode: ruby -*-

# Set the desired quantity of blocks, here.
#
MAGNITUDE=4  # 10^5 canonical blocks

VOLUMES_DIR = ENV["VOLUMES_DIR"] || '/mnt'
BASE_DIR = VOLUMES_DIR + '/mina-indexer-prod'

unless File.exist?(BASE_DIR)
  abort <<-eos
    #{BASE_DIR} must exist to perform regression tests.
    Failure.
  eos
end

puts "Productionizing with 10^#{MAGNITUDE} blocks."
deployment_exe = __dir__ + '/../start.rb'
unless system(deployment_exe, BASE_DIR, MAGNITUDE.to_s)
  abort "Failure: #{deployment_exe} #{BASE_DIR} #{MAGNITUDE}"
end
