#! /bin/sh

# Downloads Mina staking ledger logs from the Granola store.
# $1 = destination path (e.g. /mnt/mina-logs/mina_network_ledger_data)

set -x
set -eu

RESULT='Failure.'
exit_handler() {
  echo "${RESULT} Exiting." >&2
}
trap exit_handler EXIT

MY_DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"

# Wrap the command to access the Linode bucket (rclone).
#
rc() {
  time \
    rclone \
      -v -v \
      --config "$MY_DIR"/rclone.conf \
      --buffer-size 128Mi \
      --s3-access-key-id "$LINODE_OBJ_ACCESS_KEY" \
      --s3-secret-access-key "$LINODE_OBJ_SECRET_KEY" \
      "$@"
}

# Download the staking ledgers from the Granola bucket. "$1" is the destination
# directory.

# Verify that we can connect.
rc lsd linode:

# Perform the download.
rc sync --metadata linode:granola-mina-staking-ledgers "$1"
RESULT='Blocks downloaded.'

chmod -R a-wx "$1"/*
