#! /usr/bin/env -S ruby -w

# Downloads Mina staking ledger logs from the Granola store.
# ARGV[0] = destination directory

DEST = ARGV[0]

clone_exe = __dir__ + '/granola-rclone'

# Verify that we can connect.
#
args = [clone_exe, 'lsd', 'linode:']
result = system(*args)
unless result
  abort 'granola-rclone does not work'
end

# Perform the download.
#
result = system(
  clone_exe,
  'sync',
  '--metadata',
  'linode:granola-mina-staking-ledgers',
  DEST
)
unless result
  abort 'Staking ledger download failed.'
end

# Files should be read-only.
#
Dir[DEST+'/*'].each do |f|
  f.chmod(0444)
end
