#!/bin/sh

# Downloads Mina node logs of blocks (so-called "precomputed blocks") from the Granola store.
# $1 = order of magnitude of blocks desired (e.g. "4" downloads about 10^4 = 10,000 blocks)
# $2 = destination path (e.g. /mnt/mina-logs/mina_network_block_data)

set -x
set -eu

RESULT='Failure.'
exit_handler() {
  echo "${RESULT} Exiting." >&2
}
trap exit_handler EXIT

MY_DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"

# Wrap the command to access the S3 bucket (rclone).
#
rc() {
  time \
    rclone \
      -v -v \
      --config "$MY_DIR"/rclone.conf \
      --buffer-size 128Mi \
      --s3-access-key-id "$LINODE_OBJ_ACCESS_KEY" \
      --s3-secret-access-key "$LINODE_OBJ_SECRET_KEY" \
      "$@"
}

# Download the Mina blocks logs from the Granola bucket. Note that "$1" is the
# order of magnitude of the block count. So, "3" gets blocks with height up to
# 99, and "5" gets blocks with height up to 9999. "$2" is the destination
# directory.
#
if [ -d "$2" ]; then
  # The directory exists already. Search it for blocks.
  if [ -n "$(find "$2" -regextype posix-egrep -regex '.*/mainnet-9{'"$1"',}-.*')" ]; then
    RESULT='The blocks are already present. Skipping download.'
    DO_SYNC=
  else
    DO_SYNC=1
  fi
else
  DO_SYNC=1
fi
if [ '1' = "$DO_SYNC" ]; then
  # Verify that we can connect.
  rc lsd linode:

  # Perform the download.
  X="$(expr $1 + 1)"
  rc \
    sync \
    linode:granola-mina-blocks \
    --exclude '*mainnet-{{\d{'"$X"',}}}-*' \
    --dump filters \
    "$2"
  RESULT='Blocks downloaded.'
fi
