#! /bin/sh

# Downloads Mina staking ledger logs from the Granola store.
# $1 = destination directory

# For debugging:
# set -x

set -eu

RESULT='Failure.'
exit_handler() {
  echo "${RESULT} Exiting." >&2
}
trap exit_handler EXIT

MY_DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"

# Download the staking ledgers from the Granola bucket. "$1" is the destination
# directory.

# Verify that we can connect.
"$MY_DIR"/granola-rclone lsd linode:

# Perform the download.
"$MY_DIR"/granola-rclone sync --metadata linode:granola-mina-staking-ledgers "$1"
RESULT='Staking ledgers downloaded.'

chmod -R a-wx "$1"/*
