#! /usr/bin/env bash

set -eux
set -o pipefail

VER="$(git rev-parse --short=8 HEAD)"
LOG=/mnt/mina-logs/"$VER"-log
src="$(pwd)"
socket="$src"/mina-indexer.sock

wait_for_socket() {
    while true; do
        if [ -S "$socket" ]; then
            return
        fi
        sleep 30
    done
}

ephemeral_port() {
    set +e
    LOW_BOUND=49152
    RANGE=16384
    while true; do
        CANDIDATE=$(( LOW_BOUND + (RANDOM % RANGE) ))
        if ! (echo "" >/dev/tcp/127.0.0.1/${CANDIDATE}) >/dev/null 2>&1; then
            echo $CANDIDATE
            break
        fi
    done
    set -e
}

mkdir -p "$LOG"

port="$(ephemeral_port)"

./rust/target/release/mina-indexer \
  --domain-socket-path "$socket" \
  server start \
    --web-port "$port" \
    --log-level DEBUG \
    --genesis-ledger "$src"/data/genesis_ledgers/mainnet.json \
    --database-dir /mnt/mina-logs/"$VER"-database \
    --blocks-dir /mnt/mina-logs/mina_network_block_data \
    --staking-ledgers-dir /mnt/mina-logs/mina_network_ledger_data \
    --locked-supply-csv "$src"/data/locked.csv \
    --ledger-cadence 5000 \
    > "$LOG"/out \
    2> "$LOG"/err \
    &
PID=$!
wait_for_socket
./rust/target/release/mina-indexer --domain-socket-path "$socket" checkpoints create --path /mnt/mina-logs/"$VER"-snapshot
./rust/target/release/mina-indexer --domain-socket-path "$socket" shutdown
wait "$PID"
