#! /usr/bin/env -S ruby -w

BASE_DIR='/mnt/mina-indexer-dev'

if File.exist?(BASE_DIR)
  puts 'Regression testing...'
  regression_exe = __dir__ + '/../tests/regression'
  result = system(regression_exe, *ARGV)
  unless result
    abort "Failure from: #{regression_exe}"
  end
else
  abort <<-eos
    #{BASE_DIR} must exist to perform regression tests.
    Failure.
  eos
end
