#! /usr/bin/env -S ruby -w
# -*- mode: ruby -*-

START_BLOCK = ARGV[0].to_i
END_BLOCK = ARGV[1].to_i
NETWORK = ARGV[2]
DEST = ARGV[3]

require 'fileutils'

# Fetch the blocks into the blocks directory if they're not already there.
#
VOLUMES_DIR = ENV['VOLUMES_DIR'] || '/mnt'
DEV_DIR = VOLUMES_DIR + '/mina-indexer-dev'
FileUtils.mkdir_p(DEV_DIR)
BLOCKS_DIR = DEV_DIR + '/blocks'
args = [
  __dir__ + '/download-mina-blocks.rb',
  START_BLOCK.to_s,
  END_BLOCK.to_s,
  BLOCKS_DIR
]
STDERR.puts "stage-blocks issuing: #{args}"
system(*args) || abort("Failure of download-mina-blocks")

FileUtils.mkdir_p(DEST)
print 'Staging blocks'
for block in START_BLOCK..END_BLOCK
  Dir[BLOCKS_DIR + '/' + NETWORK + '-' + block.to_s + "-*.json"].each do |src|
    print '.'  # To show progress
    target = DEST + '/' + File.basename(src)
    unless File.exist?(target)
      FileUtils.cp(src, target)
    end
  end
end
puts
