#! /bin/sh

set -ex
expected='Available recipes:
    audit
    build
    clean
    default
    disallow-unused-cargo-deps
    format
    build-images
    lint
    prereqs
    test
    test-regression
    test-release
    test-unit
    test-unit-mina-rs'

if [ "$expected" = "$(just)" ]; then
  echo 2>&1 'Output matches expected. All targets present.'
else
  echo 2>&1 'Output does not match expected. Have you changed the targets?'
  exit 1
fi

just prereqs
just format
just clean
just audit
just disallow-unused-cargo-deps
just lint
just build
just test-unit

just test-unit-mina-rs
just test-regression
just test
just tier1-test
# just test-release
just build-images
