#! /bin/sh

set -eu

MAGNITUDE=5

: "${VOLUMES_DIR:=/mnt}"
TEST_DIR="$VOLUMES_DIR"/mina-indexer-test
if [ -e "$TEST_DIR" ]; then
  echo "Testing (tier 3) with 10^${MAGNITUDE} blocks."
  ./ops/deploy "$TEST_DIR"/magnitude-"$MAGNITUDE" "$MAGNITUDE" test
else
  >&2 echo "$TEST_DIR must exist to perform regression tests."
  >&2 echo 'Failure.'
  exit 1
fi
