#! /bin/sh

set -x
set -eu

# Required for subsequent steps.
#
nix develop --command just build

# Long-running regression tests normally skipped.
#
nix develop --command tests/regression test_many_blocks
# TODO: why is this not working?
# nix develop --command tests/regression test_release

# TODO: re-enable once 'git rev-parse' not required during the build
# nix build

# Test developer experience. Requires many long builds.
#
nix develop --command ops/test-justfile-targets

ops/ingest-all
