#! /usr/bin/env -S ruby -w
# -*- mode: ruby -*-

MAGNITUDE = 5

VOLUMES_DIR = ENV['VOLUMES_DIR'] || '/mnt'
TEST_DIR = VOLUMES_DIR + '/mina-indexer-test'

unless File.exist?(TEST_DIR)
  abort "Error: #{TEST_DIR} must exist to perform the tier-3 tests."
end

puts "Testing (tier 3) with 10^#{MAGNITUDE} blocks."
deploy_exe = __dir__ + '/deploy'
system(deploy_exe, TEST_DIR, MAGNITUDE.to_s) ||
  abort('tier3-test failed')
