#!/bin/sh

# Upload files from the given directory to Granola's bucket for stripped
# precomputed blocks.

set -eu

RESULT='Failure.'
exit_handler() {
    echo "${RESULT} Exiting." >&2
}
trap exit_handler EXIT

MY_DIR="$(CDPATH='' cd "$(dirname "$0")" && pwd)"

"$MY_DIR"/granola-rclone.rb sync "$1" linode-granola:blocks.minasearch.com
RESULT='Blocks uploaded.'
